### ISSUE TITLE
Не корректно отрабатывает Lombok

### ISSUE THREAD

**Issue by Straiff20** [Straiff20/HomeWork_2.3#1]
@coursar
1.Поставить плагин Lombok
2.Создать класс с аннотациями Data и AllArgsConstructor
3.Запустить delombok в gradle/task/lombok

По видео-лекции должен появится файл с конструктором, геттерами, сеттерами и т.д.

По факту все выполняется, но ничего не появляется: 
![image](https://user-images.githubusercontent.com/59826755/73938904-4d59aa80-48f9-11ea-85a6-0876362e809f.png)

Windows 10
![image](https://user-images.githubusercontent.com/59826755/73939208-0324f900-48fa-11ea-95a3-8c79b1147ac1.png)

IDE
![image](https://user-images.githubusercontent.com/59826755/73939345-54cd8380-48fa-11ea-9562-53e1231e5d5f.png)

**Comment by ArRomanov** [comment]
Проверьте, что у вас все так же

![checkbox](https://user-images.githubusercontent.com/23121947/73947522-a3821a00-4908-11ea-8a96-5e12b05e4763.png)
![model](https://user-images.githubusercontent.com/23121947/73947523-a4b34700-4908-11ea-921c-e616e314a17a.png)
![using](https://user-images.githubusercontent.com/23121947/73947525-a4b34700-4908-11ea-96a9-bb881f872aa9.png)

**Comment by Straiff20** [comment]
Да, все так(кроме Data. У меня lambok.Data). Как тогда мне зайти в этот файл, который создает delambok и поправить toString?

**Comment by Straiff20** [comment]
И еще в настройках у меня Gradle Imported есть, которого у Вас нет на скринах

**Comment by ArRomanov** [comment]
Вот ваш актуальный класс - https://github.com/Straiff20/HomeWork_2.3/blob/master/src/test/java/netology/RegCardInfo.java.
Вам нужно там добавить `import lombok.Data;` и изменить аннотацию на **@Data** и у вас все должно заработать.
Больше я ничего не изменял, остальное все осталось так как было

**Comment by Straiff20** [comment]
Не сгенерировался файл все равно
![image](https://user-images.githubusercontent.com/59826755/74007828-59dd1200-4990-11ea-9fe7-75c3ea193e1d.png)

**Comment by Straiff20** [comment]
Проблема решена. У меня файлы сгенерировались не в build/delombok/test/netology, как в видео уроке.
Они у мена сгенерировались в build/classes/java/test/netology.
